# Generated by Django 4.0.4 on 2022-05-16 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Match',
            new_name='MatchOfertaDemanda',
        ),
        migrations.AlterModelOptions(
            name='matchofertademanda',
            options={'verbose_name': 'Match Oferta Demanda', 'verbose_name_plural': 'Match Oferta Demanda'},
        ),
    ]
