# Generated by Django 4.0.4 on 2022-05-16 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_match_matchofertademanda_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustriaPyme',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombreindustria', models.CharField(max_length=50)),
                ('descripcionindustria', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Industria Pyme',
                'verbose_name_plural': 'Industria Pyme',
            },
        ),
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombretipousuario', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Tipo Usuario',
                'verbose_name_plural': 'Tipo Usuario',
            },
        ),
        migrations.AlterModelOptions(
            name='categoriademandaoferta',
            options={'verbose_name': 'Categoria Demanda Oferta', 'verbose_name_plural': 'Categoria Demanda Oferta'},
        ),
        migrations.AlterModelOptions(
            name='demandapyme',
            options={'verbose_name': 'Demanda Pyme', 'verbose_name_plural': 'Demanda Pyme'},
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=20)),
                ('idtipousuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipousuario')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuario',
            },
        ),
    ]
