# Generated by Django 4.0.4 on 2022-05-16 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_industriapyme_tipousuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pyme',
            name='idindustriapyme',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.industriapyme'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pyme',
            name='idusuario',
            field=models.ForeignKey(default=1234, on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
            preserve_default=False,
        ),
    ]
